### ISSUE TITLE
Log Out not working

### ISSUE THREAD

**Issue by isaacgaff** [insidegui/PodcastMenu#14]
Log out link is not working (for me).

**Comment by insidegui** [comment]
Overcast's website shows an alert confirmation before logging out, that's why it wasn't working in the app. Since I don't want to support javascript alerts, I added a "Log Out" option on the menu 😉

<img width="220" alt="screen shot 2017-04-09 at 12 27 26" src="https://cloud.githubusercontent.com/assets/67184/24838527/f471f786-1d1f-11e7-9917-a089af6f41a9.png">
